name: Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.0

      - name: Build and Run Docker Container
        run: |
          docker build -t my-selenium-tests .
          docker run -t --name selenium-tests my-selenium-tests
        continue-on-error: true
    
      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: pytest-html-report
          path: ./report/report.html

